name: Build and Sign Nextcloud APK

on:
  push:
    branches: [ "disruptibe-branding" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar y Firmar
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Configurar Java 21 y Caché de Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # <-- Esta es la instrucción que activa la caché

      - name: Aceptar licencias del SDK de Android
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Instalar Android Build Tools
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

      - name: Instalar Android NDK
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Compilar el APK (Release)
        run: ./gradlew assembleGenericRelease

      - name: Firmar el APK con los Secrets
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "33.0.2"
        with:
          releaseDirectory: app/build/outputs/apk/generic/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Subir el APK final para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Nextcloud-Release-APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
